version: '3.9'

services:
  nextjs:
    build: .
    environment:
      - NODE_ENV=production
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ros
